### ISSUE TITLE
grayscale not working properly on IOS

### ISSUE THREAD

**Issue by madaoCN** [brettferdosi/grayscale#3]
I run the code as following:
```
let enabled = MADisplayFilterPrefGetCategoryEnabled(SYSTEM_FILTER) &&
             (MADisplayFilterPrefGetType(SYSTEM_FILTER) == GRAYSCALE_TYPE)
if enabled {
    MADisplayFilterPrefSetCategoryEnabled(SYSTEM_FILTER, false)
} else {
    MADisplayFilterPrefSetType(SYSTEM_FILTER, GRAYSCALE_TYPE)
    MADisplayFilterPrefSetCategoryEnabled(SYSTEM_FILTER, true)
}
//_UniversalAccessDStart(UNIVERSALACCESSD_MAGIC)
CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(), CFNotificationName.init("com.apple.mediaaccessibility.displayFilterSettingsChanged" as CFString), nil, nil, true)
```

and got this error:
![image](https://user-images.githubusercontent.com/12007985/97835330-dd0b7880-1d14-11eb-8a5c-3f2f35f631b9.png)

```
Couldn't write value for key __Color__.MADisplayFilterCategoryEnabled in CFPrefsPlistSource<0x2808f4d80> (Domain: com.apple.mediaaccessibility, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
```
It seems like no access to wirte value in CFPrefsPlistSource. 
so, how to make the grayscale working on IOS? Thanks.

**Comment by brettferdosi** [comment]
Hi, I haven't looked into what is required to toggle the grayscale filter on iOS yet because iOS has native support for binding that functionality to a shortcut. For this application I reverse engineered the way System Preferences toggles the grayscale filter on macOS - I would be surprised if the same technique works on iOS.

As you say, the error you're seeing suggests that the app you copied the code snippet into doesn't have the right entitlements to modify the plist file. Take a look at the entitlements here: https://github.com/brettferdosi/grayscale/blob/master/Resources/grayscale.entitlements, specifically

```
        <key>com.apple.security.temporary-exception.files.home-relative-path.read-write</key>
	<array>
		<string>/Library/Preferences/com.apple.universalaccess.plist</string>
		<string>/Library/Preferences/com.apple.mediaaccessibility.plist</string>
	</array>
```

Hope this helps, and please let me know what ends up working for you on iOS.
